[package]
name = "cryptocurrency-tracker"
version = "0.1.0"
authors = ["Joe Roberts <joe@resin.io>"]

[dependencies]
clap = "2.25.0"
hyper = "0.10.12"
hyper-native-tls = "0.2.4"
serde = "1.0.9"
serde_json = "1.0.2"
serde_derive = "1.0.9"
strfmt = "0.1.5"
error-chain = "0.10.0"
